- name: add ssh key for simeone
  authorized_key:
    user: simeone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID4gawgXkigSswqjFXBHjedBLzbhuC3jI6OsO85InE/0 ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd

