# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "vagrant-ubuntu-trusty64"
      vb.memory = "1024"
      vb.cpus = "2"
    end
    config.vm.network "private_network", ip: "192.168.56.10"
    # config.vm.network "public_network"
    config.vm.synced_folder ".", "/var/www/html"
    config.vm.provision "shell", path: "bootstrap.sh"
end


Vagrant.configure(2) do |config|
     config.vm.box = "centos/7"
     config.vm.hostname = "control"
     config.vm.network "private_network", ip: "192.168.50.10"
     config.vm.synced_folder "src/", "/var/www/html"
     config.vm.provision "shell", path: "bootstrap.sh"
     config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "2"
     end
end